"""Initial migration

Revision ID: 04af67d526f1
Revises: 
Create Date: 2025-05-18 22:29:21.470569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04af67d526f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True, comment='login'),
    sa.Column('list_acc', sa.TEXT(), nullable=True, comment='separes par -'),
    sa.Column('droit', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True, comment='password'),
    sa.Column('pass_hash', sa.String(length=60), nullable=True, comment='php PASSWORD_BCRYPT'),
    sa.Column('cle', sa.String(length=40), nullable=True),
    sa.Column('date_cle', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('op_acc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=11), nullable=True),
    sa.Column('nom', sa.String(length=50), nullable=True),
    sa.Column('debut', sa.DATE(), nullable=True),
    sa.Column('fin', sa.DATE(), nullable=True),
    sa.Column('producteurs', sa.TEXT(), nullable=True),
    sa.Column('repartition', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('op_acc')
    op.drop_table('membres')
    # ### end Alembic commands ###
